<a href="https://colab.research.google.com/github/ASAthigiri/ASAthigiri/blob/main/DL_EX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ex: 1 IMPLEMENT SIMPLE PROGRAMS LIKE VECTOR ADDITION IN TENSORFLOW


In [1]:
import tensorflow as tf
vector1 = tf.constant([2.0, 3.0, 4.0])
print(vector1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [2]:
vector2 = tf.constant([3.0, 4.0, 5.0])
print(vector2)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float32)


In [3]:
print(tf.add(vector1,vector2))

tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)


In [4]:
print(vector1*vector2)


tf.Tensor([ 6. 12. 20.], shape=(3,), dtype=float32)


In [5]:
print(tf.tensordot(vector1,vector2,axes=1))


tf.Tensor(38.0, shape=(), dtype=float32)


In [6]:
a = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
b = tf.constant([1., 2., 3.])
c = tf.tensordot(a, b, axes=1)
print(c)

tf.Tensor([14. 32. 50.], shape=(3,), dtype=float32)


EX: 2 IMPLEMENT A SIMPLE PROBLEM LIKE REGRESSION MODEL IN KERAS
